---
- hosts: all
  become: yes
  tasts:
  - name: i want to install webserver on ubuntu node
    apt:
      name: apache
      state: present
  - name: i want to install tree on ubuntu node
    apt:
      name: tree
      state: present